spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/silentvault_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: silentvault-super-top-secret-key-123456789!
  expirationMs: 86400000

server:
  port: 8080